// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_id.proto

#include "msg_id.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace game {
}  // namespace game
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_msg_5fid_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_msg_5fid_2eproto = nullptr;
const uint32_t TableStruct_msg_5fid_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_msg_5fid_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014msg_id.proto\022\004game*\236\001\n\014message_type\022\017\n"
  "\013msg_c2s_req\020\000\022\020\n\013msg_s2c_ack\020\200 \022\020\n\013msg_"
  "c2s_brd\020\200@\022\020\n\013msg_s2c_brd\020\200`\022\021\n\013msg_s2s_"
  "req\020\200\200\001\022\021\n\013msg_s2s_ack\020\200\240\001\022\021\n\013msg_s2s_br"
  "d\020\200\300\001\022\016\n\010msg_mask\020\200\340\003*\377\006\n\nmessage_id\022\013\n\007"
  "id_none\020\000\022\017\n\013id_ping_req\020\001\022\020\n\013id_ping_ac"
  "k\020\201 \022\020\n\014id_login_req\020\002\022\021\n\014id_login_ack\020\202"
  " \022\020\n\014id_match_req\020\003\022\021\n\014id_match_ack\020\203 \022\025"
  "\n\021id_enter_room_req\020\004\022\026\n\021id_enter_room_a"
  "ck\020\204 \022\017\n\013id_move_req\020\005\022\020\n\013id_move_ack\020\205 "
  "\022\020\n\013id_move_brd\020\205`\022\023\n\rid_s_ping_req\020\201\200\001\022"
  "\023\n\rid_s_ping_ack\020\201\240\001\022\034\n\026id_s_gate_regist"
  "er_req\020\202\200\001\022\034\n\026id_s_gate_register_ack\020\202\240\001"
  "\022\034\n\026id_s_gate_register_brd\020\202\300\001\022\037\n\031id_s_s"
  "ervice_register_req\020\203\200\001\022\037\n\031id_s_service_"
  "register_ack\020\203\240\001\022\035\n\027id_s_service_update_"
  "req\020\204\200\001\022\035\n\027id_s_service_update_ack\020\204\240\001\022\033"
  "\n\025id_s_gate_forward_brd\020\205\300\001\022 \n\032id_s_serv"
  "ice_subscribe_req\020\206\200\001\022 \n\032id_s_service_su"
  "bscribe_ack\020\206\240\001\022 \n\032id_s_service_subscrib"
  "e_brd\020\206\300\001\022\035\n\027id_s_client_forward_brd\020\207\300\001"
  "\022\032\n\024id_s_kick_client_req\020\210\200\001\022\032\n\024id_s_kic"
  "k_client_ack\020\210\240\001\022\035\n\027id_s_client_offline_"
  "brd\020\211\300\001\022\024\n\016id_s_login_req\020\212\200\001\022\024\n\016id_s_lo"
  "gin_ack\020\212\240\001\022\032\n\024id_s_login_logic_req\020\213\200\001\022"
  "\032\n\024id_s_login_logic_ack\020\213\240\001\022\030\n\022id_s_get_"
  "logic_req\020\214\200\001\022\030\n\022id_s_get_logic_ack\020\214\240\001b"
  "\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_msg_5fid_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fid_2eproto = {
    false, false, 1087, descriptor_table_protodef_msg_5fid_2eproto,
    "msg_id.proto",
    &descriptor_table_msg_5fid_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_msg_5fid_2eproto::offsets,
    nullptr, file_level_enum_descriptors_msg_5fid_2eproto,
    file_level_service_descriptors_msg_5fid_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fid_2eproto_getter() {
  return &descriptor_table_msg_5fid_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fid_2eproto(&descriptor_table_msg_5fid_2eproto);
namespace game {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* message_type_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_msg_5fid_2eproto);
  return file_level_enum_descriptors_msg_5fid_2eproto[0];
}
bool message_type_IsValid(int value) {
  switch (value) {
    case 0:
    case 4096:
    case 8192:
    case 12288:
    case 16384:
    case 20480:
    case 24576:
    case 61440:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* message_id_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_msg_5fid_2eproto);
  return file_level_enum_descriptors_msg_5fid_2eproto[1];
}
bool message_id_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 4097:
    case 4098:
    case 4099:
    case 4100:
    case 4101:
    case 12293:
    case 16385:
    case 16386:
    case 16387:
    case 16388:
    case 16390:
    case 16392:
    case 16394:
    case 16395:
    case 16396:
    case 20481:
    case 20482:
    case 20483:
    case 20484:
    case 20486:
    case 20488:
    case 20490:
    case 20491:
    case 20492:
    case 24578:
    case 24581:
    case 24582:
    case 24583:
    case 24585:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace game
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
